#! /bin/env zsh
#
# deploy.sh
# Copyright (C) 2021 matthew <matthew@matthew-VirtualBox>
#
# Distributed under terms of the MIT license.
#

if [ -d "$1" -a -n "$1" ]
then
  cd $1
  shift 1
fi

for file in ./deploy*
do
  if ./$file $@
  then
    exit
  fi
done
