#! /bin/env zsh
#
# deploy.sh
# Copyright (C) 2021 matthew <matthew@matthew-VirtualBox>
#
# Distributed under terms of the MIT license.
#

if [ -d "$1" -a -n "$1" ]
then
  cd $1
  shift 1
fi

DEPLOY_SCRIPTS=("./deploy" "./deploy.sh")

while [[ "$PWD" != "/" ]]
do
  for file in $DEPLOY_SCRIPTS
  do
    # If file exists, execute file, and exit if successful
    [ -f $file ] && ./$file $@ && exit
  done
  cd ..
done
