#!/bin/bash

if [[ "$NVIM_LISTEN_ADDRESS" != "" ]]
then
  # Open vim
  ARGS="RemoteOpen(\"$PWD\", \"$@\")"
  nvim --server $NVIM_LISTEN_ADDRESS --remote-expr "$ARGS" 2>&1 > /dev/null
  # echo "$@"
  RED=""
  while [[ "$RED" != "NVIM_EDITOR_CLOSE" ]]
  do
    read -e RED
  done
else
  nvim $@
fi
