#!/bin/bash

if [[ "$NVIM_LISTEN_ADDRESS" != "" ]]
then
  # Open vim
  ARGS="RemoteOpen(\"$PWD\", \"$@\")"
  nvim --server $NVIM_LISTEN_ADDRESS --remote-expr "$ARGS" 2>&1 > /dev/null
  # echo "$@"
  read RED
else
  nvim $@
fi
