#!/bin/bash

apt install \
  curl \
  neovim \
  kitty \
  zsh \
  make \
  htop \
  g++ \
  gcc \
  docker \
  docker-compose \
  autojump \
  clangd-9 \
  fd-find \
  git \
  gparted \
  net-tools

mkdir -p $HOME/.local/bin/
(# Executed in subshell so fdfind WILL be found
  ln -s $(which fdfind) ~/.local/bin/fd
)
