#!/bin/bash

apt update

apt install curl
apt install neovim
apt install kitty
apt install zsh
apt install htop
apt install gcc g++
apt install pkg-config make
apt install docker docker-compose \
apt install nodejs npm
apt install autojump
apt install fd-find
apt install git
apt install gparted
apt install net-tools
apt install golang
apt install ncdu
apt install ripgrep

go install github.com/jesseduffield/lazygit@latest

sudo npm install --global yarn

mkdir -p $HOME/.local/bin/
(# Executed in subshell so fdfind WILL be found
  ln -s $(which fdfind) ~/.local/bin/fd
)
