#!/bin/bash

apt update

apt install \
  curl \
  neovim \
  kitty \
  zsh \
  make \
  htop \
  g++ \
  gcc \
  pkg-config \
  docker \
  docker-compose \
  nodejs \
  npm \
  autojump \
  clangd-9 \
  fd-find \
  git \
  gparted \
  net-tools \
  golang \
  ncdu \
  ripgrep

go install github.com/jesseduffield/lazygit@latest

sudo npm install --global yarn

mkdir -p $HOME/.local/bin/
(# Executed in subshell so fdfind WILL be found
  ln -s $(which fdfind) ~/.local/bin/fd
)
