#!/bin/bash

pacman -Syu

pacman -S kitty
pacman -S fish
pacman -S git
pacman -S nodejs npm
pacman -S go

go install github.com/jesseduffield/lazygit@latest

sudo npm install --global yarn

mkdir -p $HOME/.local/bin/
