#!/bin/bash

function prevent_overwrite() {
	local CURPOS
	echo -en "\E[6n"
	read -sdR CURPOS
	CURPOS=${CURPOS#*[*;}
	if [[ ${CURPOS} > 1 ]]
	then
		echo ""
	fi
}

set_bash_prompt(){
	prevent_overwrite
	echo -ne "\033]0;${PWD/#$HOME/\~} \007"
}

PROMPT_COMMAND=set_bash_prompt
case ${TERM} in
	xterm*|rxvt*|Eterm|aterm|kterm|gnome*)
# Enable thefuck
PS1='\[\033[G\033[K\033[01;32m\]\u@manjaro-hp\[\033[01;36m\]│\W\[\033[01;32m\]$(get_screen_name_prompt_color)\
$(echo -e "$(~/bin/install/pretty-git-prompt/target/release/pretty-git-prompt)")\
$(get_venv_name_prompt_color)\[\033[00m\]\$ '
		;;
	screen*|*)
PS1='\[\033[01;32m\]\u@manjaro-hp\[\033[01;36m\]:\W\[\033[01;32m\]$(get_screen_name_prompt_color)\
$(echo -e "$(~/bin/install/pretty-git-prompt/target/release/pretty-git-prompt)")\
$(get_venv_name_prompt_color)\[\033[00m\]\$ '
	
		;;
esac

# eval $(thefuck --enable-experimental-instant-mode --alias)
LS_COLORS="ex=01;33:di=01;36"

