#!/bin/zsh

alias cp="cp -i"            # confirm before overwriting something
alias df='df -h'            # human-readable sizes
alias free='free -m'        # show sizes in MB
alias more=less


# my aliases
alias ls='ls --color=tty --group-directories-first'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias sl='sl -e'
# Some cool aliases, with cloned completes
alias ddp='dd status=progress bs=1024k '
alias op='xdg-open'

if [ -f $HOME/bin/install/arg-adjuster/target/release/p7zip-args ]
then
	alias 7z="$HOME/bin/install/arg-adjuster/target/release/p7zip-args"
fi

case $TERM in 
		*kitty)
				alias clip='kitty +kitten clipboard'
				alias paste='kitty +kitten clipboard --get-clipboard'
				;;
		*)
				alias clip='xclip -i'
				alias paste='echo "$(xclip -o -rmlastnl)"'
				;;
esac

# `command` is a bash built-in that executes the given shell command
# `sudo` is the same, but executes the command as a different user
#complete -F _command sudo

if type wslsys &> /dev/null
then
	if wslsys &> /dev/null
	then
		alias firefox='wsl_run /mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe'
	fi
fi

if type zathura &> /dev/null
then
	alias zathura='zathura --fork'
fi

timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time -p $shell -i -c exit; done
}

function ghost() {
	cd ~
	nvim +GhostStart
}
